export { default as code } from "./Pre";
export { default as inlineCode } from "./Code";
export { default as p } from "./Paragraph";
export { Heading1 as h1 } from "./Heading";
export { Heading2 as h2 } from "./Heading";
export { Heading3 as h3 } from "./Heading";
export { Heading4 as h4 } from "./Heading";
export { Heading5 as h5 } from "./Heading";
export { Heading6 as h6 } from "./Heading";
