on: push
name: Deploy Workflow
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: nuxt/actions-yarn@master
      with:
        args: install
    - name: Lint
      uses: nuxt/actions-yarn@master
      with:
        args: lint
    - name: Build
      uses: nuxt/actions-yarn@master
      with:
        args: build
    - name: Export
      uses: nuxt/actions-yarn@master
      with:
        args: export
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v1.0.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./out
      with:
        args: deploy
